apiVersion: eventstreams.ibm.com/v1alpha1
kind: KafkaConnector
metadata:
  name: mq-sink-connector
  namespace: cp4i
  labels:
    eventstreams.ibm.com/cluster: es-prod-cluster
spec:
  class: com.ibm.eventstreams.connect.mqsink.MQSinkConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    topics: MQ.TOPIC
    mq.queue.manager: <>
    mq.connection.name.list: <host>(443)
    mq.channel.name: <>
    mq.queue: <>
    mq.message.builder: com.ibm.eventstreams.connect.mqsink.builders.DefaultMessageBuilder
    mq.ssl.cipher.suite: '*TLS12'
    mq.ssl.truststore.location: /opt/kafka/external-configuration/mq-truststore-cert/client.jks
    mq.ssl.truststore.password: passw0rd