apiVersion: eventstreams.ibm.com/v1alpha1
kind: KafkaConnector
metadata:
  name: mq-source-connector
  namespace: cp4i
  labels:
    eventstreams.ibm.com/cluster: es-prod-cluster
spec:
  class: com.ibm.eventstreams.connect.mqsource.MQSourceConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    topic: MQ.TOPIC
    mq.queue.manager: <>
    mq.connection.name.list: <hostname>(443)
    mq.channel.name: <>
    mq.queue: <>
    mq.record.builder: com.ibm.eventstreams.connect.mqsource.builders.DefaultRecordBuilder
    mq.ssl.cipher.suite: '*TLS12'
    mq.ssl.truststore.location: /opt/kafka/external-configuration/mq-truststore-cert/client.jks
    mq.ssl.truststore.password: passw0rd